// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPtFAHuEKhV62zS8TfhYje8WwIZUxujQA',
    appId: '1:353396631731:ios:6fe9389fa9bbed5931e8c6',
    messagingSenderId: '353396631731',
    projectId: 'filemanager-446f0',
    storageBucket: 'filemanager-446f0.firebasestorage.app',
    iosBundleId: 'com.example.fileManagerInternetApplicationsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPtFAHuEKhV62zS8TfhYje8WwIZUxujQA',
    appId: '1:353396631731:ios:6fe9389fa9bbed5931e8c6',
    messagingSenderId: '353396631731',
    projectId: 'filemanager-446f0',
    storageBucket: 'filemanager-446f0.firebasestorage.app',
    iosBundleId: 'com.example.fileManagerInternetApplicationsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCodCsuw9P8BhZ_iRffQyO-ua9B4We06K0',
    appId: '1:353396631731:web:40349d4169a337e431e8c6',
    messagingSenderId: '353396631731',
    projectId: 'filemanager-446f0',
    authDomain: 'filemanager-446f0.firebaseapp.com',
    storageBucket: 'filemanager-446f0.firebasestorage.app',
    measurementId: 'G-KYGJ947665',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCodCsuw9P8BhZ_iRffQyO-ua9B4We06K0',
    appId: '1:353396631731:web:40349d4169a337e431e8c6',
    messagingSenderId: '353396631731',
    projectId: 'filemanager-446f0',
    authDomain: 'filemanager-446f0.firebaseapp.com',
    storageBucket: 'filemanager-446f0.firebasestorage.app',
    measurementId: 'G-KYGJ947665',
  );

}