const Map<String, String> ar = {
  'Add New Group': 'انشاء مجموعة جديدة',
  'Groups': 'المجموعات',
  'My Booked Files': 'ملفاتي المحجوزة',
  'Joining Requests to My Groups': 'طلبات الانضمام إلى مجموعاتي',
  'Joining Requests': 'طلبات دعوة الانضمام',
  'Home': 'الصفحة الرئيسية',
  'My Booked file': 'ملفاتي المحجوزة',
  'change language': 'تغيير اللغة',
  'Light/Dark': 'الوضع المظلم / الوضع الفاتح',
  'User Name': 'اسم المستخدم',
  'file manager': 'مدير الملفات',
  'profile': 'الملف الشخصي',
  'if you want to create your own group ': 'إذا كنت ترغب في إنشاء مجموعتك الخاصة',
  'see all group and your group and joined group ': 'عرض جميع المجموعات ومجموعاتك والمجموعات التي انضممت إليها',
  'all files you are check in ': 'جميع الملفات التي قمت بحجزها',
  'user who send request to join one of your groups': 'المستخدمين الذين أرسلوا طلبات للانضمام إلى مجموعاتك',
  'user invite you to join there groups': 'المستخدمين الذين دعوك للانضمام إلى مجموعاتهم',
  'create group': 'إنشاء مجموعة',
  'enter group name': 'أدخل اسم المجموعة',
  'error': 'خطأ',
  'please enter a group name': 'الرجاء إدخال اسم المجموعة',
  'success': 'نجاح',
  'group created successfully': 'تم إنشاء المجموعة بنجاح',
  'failed to create group': 'فشل في إنشاء المجموعة',
  'create': 'إنشاء',
  'search groups': 'البحث عن المجموعات',
  'my groups': 'مجموعاتي',
  'joined groups': 'المجموعات المنضم إليها',
  'public groups': 'المجموعات العامة',
  'no groups available': 'لا توجد مجموعات متاحة',
  'owner': 'المالك',
  'unknown': 'غير معروف',
  'join request': 'طلب انضمام',
  'no_groups_available': 'لا توجد مجموعات متاحة',
  'no_join_requests_available': 'لا توجد طلبات انضمام متاحة',
  'joining_requests_to_my_groups': 'طلبات الانضمام إلى مجموعاتي',
  'requests_for_group': 'طلبات الانضمام لـ ',
  'requested_on': 'تمت الطلبات في: ',
  'No Joining Requests Available': 'لا توجد طلبات انضمام متاحة', // نص بالعربي
  'Owner': 'المالك: ',
  'Sent At': 'تم الإرسال في: ',
  'Role': 'الدور',
  'Email': 'البريد الإلكتروني',
  'Change Password': 'تغيير كلمة المرور',
  'Logout': 'تسجيل الخروج',
  "add_file": "إضافة ملف",
  "invite_user": "دعوة مستخدم",
  "file_requests": "طلبات الملفات",
  "remove_user": "إزالة مستخدم",
  "edit_group": "تعديل المجموعة",
  "delete_group": "حذف المجموعة",
  "leave_group": "مغادرة المجموعة",
  "files": "الملفات",
  "members": "الأعضاء",
  "no_group_selected": "لم يتم تحديد مجموعة.",
  "no_files_uploaded": "لا توجد ملفات تم رفعها.",
  "check_in_more_than_one_file": "تحقق من أكثر من ملف",
  "no_members_found": "لم يتم العثور على أعضاء.",
  "choose_file_to_upload": "اختر الملف الذي تريد رفعه",
  "select_file": "اختيار ملف",
  "no_file_selected": "لم يتم اختيار ملف",
  "press_to_upload": "اضغط للرفع",
  "invite_user_to_group": "دعوة المستخدم إلى المجموعة",
  "users": "المستخدمين",
  "no_users_available": "لا يوجد مستخدمين متاحين",
  "invite": "دعوة",
  "please_select_a_user": "يرجى اختيار مستخدم.",
  "invalid_data_provided": "تم توفير بيانات غير صحيحة. يرجى المحاولة مرة أخرى.",
  "edit_group_settings": "تعديل إعدادات المجموعة",
  "enter_new_group_name": "أدخل اسم المجموعة الجديد",
  "private_folder": "مجلد خاص",
  "disable_add_file": "تعطيل إضافة ملفات",
  "update_settings": "تحديث الإعدادات",
};
