const Map<String, String> en = {
  'Add New Group': 'Add New Group',
  'Groups': 'Groups',
  'My Booked Files': 'My Booked Files',
  'Joining Requests to My Groups': 'Joining Requests to My Groups',
  'Joining Requests': 'Joining Requests',
  'Home': 'Home',
  'My Booked file': 'My Booked Files',
  'change language': 'Change Language',
  'Light/Dark': 'Light/Dark',
  'User Name': 'User Name',
  'file manager': 'File Manager',
  'profile': 'Profile',
  'if you want to create your own group ': 'If you want to create your own group',
  'see all group and your group and joined group ': 'See all groups, your groups, and joined groups',
  'all files you are check in ': 'All files you have checked in',
  'user who send request to join one of your groups': 'Users who sent requests to join your groups',
  'user invite you to join there groups': 'Users who invited you to join their groups',
  'create group': 'Create a Group',
  'enter group name': 'Enter group name',
  'error': 'Error',
  'please enter a group name': 'Please enter a group name',
  'success': 'Success',
  'group created successfully': 'Group created successfully',
  'failed to create group': 'Failed to create group',
  'create': 'Create',
  'search groups': 'Search Groups',
  'my groups': 'My Groups',
  'joined groups': 'Joined Groups',
  'public groups': 'Public Groups',
  'no groups available': 'No groups available',
  'owner': 'Owner',
  'unknown': 'Unknown',
  'join request': 'Join Request',
  'no_groups_available': 'No Groups Available',
  'no_join_requests_available': 'No join requests available',
  'joining_requests_to_my_groups': 'Joining Requests to My Groups',
  'requests_for_group': 'Requests for ',
  'requested_on': 'Requested on: ',
  'No Joining Requests Available': 'No Joining Requests Available', // نص انجليزي
  'Owner': 'Owner: ',
  'Sent At': 'Sent At: ',
  'Role': 'Role',
  'Email': 'Email',
  'Change Password': 'Change Password',
  'Logout': 'Logout',
  "add_file": "Add File",
  "invite_user": "Invite User",
  "file_requests": "File Requests",
  "remove_user": "Remove User",
  "edit_group": "Edit Group",
  "delete_group": "Delete Group",
  "leave_group": "Leave Group",
  "files": "Files",
  "members": "Members",
  "no_group_selected": "No group selected.",
  "no_files_uploaded": "No files uploaded.",
  "check_in_more_than_one_file": "Check in more than one file",
  "no_members_found": "No members found.",
"choose_file_to_upload": "Choose the file you want to upload",
"select_file": "Select File",
"no_file_selected": "No file selected",
"press_to_upload": "Press to upload",
  "invite_user_to_group": "Invite User to Group",
  "users": "Users",
  "no_users_available": "No Users Available",
  "invite": "Invite",
  "please_select_a_user": "Please select a user.",
  "invalid_data_provided": "Invalid data provided. Please try again.",
  "edit_group_settings": "Edit Group Settings",
  "enter_new_group_name": "Enter new group name",
  "private_folder": "Private Folder",
  "disable_add_file": "Disable Add File",
  "update_settings": "Update Settings",
};
